name: CI

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build kvault and test kvault (Android)
        run: ./gradlew build test
      - name: Build testapp and test kvault (iOS)
        run: |
          cd iostests
          sudo xcode-select -switch /Applications/Xcode_14.2.app
          xcodebuild clean test -project TestApp.xcodeproj -scheme TestApp -destination "platform=iOS Simulator,OS=16.3,name=iPhone 14" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Upload test result
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: build/reports/
