name: CI

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build kvault and test kvault (Android)
        run: ./gradlew build test -x iosX64Test
      - name: Build testapp and test kvault (iOS)
        run: |
          cd iostests
          sudo xcode-select -switch /Applications/Xcode_11.5.app
          xcodebuild clean test -project TestApp.xcodeproj -scheme TestApp -destination "platform=iOS Simulator,OS=13.5,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Upload test result
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: reports
          path: kvault/build/reports/
